### PR TITLE
Refactor API Route Names

### PR DESCRIPTION
**Pull request by matthewkohlhaas**
Refactors the back end route names to better match RESTful service conventions. Don't approve this PR util #16 has been approved first.

### CODE REVIEW

**Comment by matthewkohlhaas** [comment]
If we want total consistency the we'll have to go with `app.route('/').get('')` given that we might want to add the option POST to the same route. You can see an example of this for the route `listings`.

**Comment by ScottSWolfe** [comment]
@matthewkohlhaas You can do `post` and `get` on the same route using my preferred method. You just do `app.get('/', getStuff);` and `app.post('/', postStuff);`

**Comment by matthewkohlhaas** [comment]
But, then you have to repeat the route name, making the code less dry

**Comment by ScottSWolfe** [comment]
Yeah, though I think it's more clear. But I guess it's just pros and cons either way, and really not a big deal. I'll go ahead and approve this.

**Comment by matthewkohlhaas** [comment]
I will leave the routes with a single request methods as `app.post(...)` and `app.get(...)` and keep the multi-method routes as `app.route(...).get(...).post(...)...`. To make the best use of each approach, I'm okay with a little inconsistency.

**Pull request merged**
